// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function DeleteItem(arg1:string):Promise<void>;

export function GetItems():Promise<Array<types.Item>>;

export function SaveItem(arg1:types.Item):Promise<void>;

export function UpdateItem(arg1:types.Item):Promise<void>;
