// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteItem(arg1) {
  return window['go']['storage']['Handler']['DeleteItem'](arg1);
}

export function GetItems() {
  return window['go']['storage']['Handler']['GetItems']();
}

export function SaveItem(arg1) {
  return window['go']['storage']['Handler']['SaveItem'](arg1);
}

export function UpdateItem(arg1) {
  return window['go']['storage']['Handler']['UpdateItem'](arg1);
}
